input.onButtonPressed(Button.B, function () {
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Double))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Double))
    basic.pause(10)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(30)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Double))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(330, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(294, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Half))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(330, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(294, music.beat(BeatFraction.Double))
    basic.pause(10)
    music.playTone(294, music.beat(BeatFraction.Whole))
})
basic.forever(function () {
	
})
